sudo: false
language: python
python:
  - "3.7"
  - "3.6"

jobs:
  include:
    - stage: lint
      script: make lint

before_install:
  - make get-deps
  - pip install codecov

after_success:
  - codecov

install: pip install -r requirements.txt

stages:
  - lint
  - test

script:
  - make test
  - make coverage
  - make report
