sudo: false
language: python
env:
  global:
    - CODECOV_TOKEN=5732b0fd-8991-4aa3-95e5-faa23803ffa7
python:
  - "3.7"
  - "3.6"

before_install:
  - make get-deps

after_success:
  - bash <(curl -s https://codecov.io/bash)

install: pip install -r requirements.txt
script: tox
