apiVersion: v1
kind: Service
metadata:
  name: spellcheckapp-web-service
  labels:
    run: spellcheckapp-web-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: spellcheckapp
